### PR TITLE
New tests for Null Equality Joins

### PR DESCRIPTION
**Pull request by khurram-faraaz**
Hello Abhishek,

I have added tests for null equality join support in Drill 1.9.0
Please review and comment and merge if tests look good to you.
You should be looking at these tests - framework/resources/Functional/joins/nulleqjoin/*.q

I have a clean pre-commit run, for which I will share the link.

P.S: I have also fixed some other tests in window_functions/tpcds dir, where I disabled the failing tests.

Thanks,
Khurram

### CODE REVIEW

**Comment by Agirish** [comment]
Can we mark all failing tests with .sql.fail extension? We plan to add a feature to the framework in the near future where we can automatically execute any tests marked with .fail. And it would be good to have consistent tests, for the feature to work seamlessly. 

All of us should revisit existing tests as well, when we find time and modify any non-conformant tests.

**Comment by Agirish** [comment]
Please rebase your branch on mapr master, squash commits before you create a PR going forward. I can help share the commands to use for the same - it should be pretty straightforward.

**Comment by Agirish** [comment]
Can you please share why there are new tests in Functional/convert as well? If they aren't related to Null Eq Joins, please create a separate PR going forward.

**Comment by Agirish** [comment]
+1. I'll squash and commit your changes - but do address the comments.

**Comment by kfaraaz** [comment]
sure thanks. Yes I did add a test into Functional/convert that was part of a JIRA verification, wanted to club with this commit so. In future I will use separate PRs.

Thanks,
Khurram

**Comment by kfaraaz** [comment]
I always follow these steps (below) before I add my commit, let me know if I should be doing something different before committing my changes.

git fetch upstream
git merge upstream/master
git push origin master

**Pull request merged**
