### PR TITLE
MD-2954: Fixed TPCDS100 hive datagen script

### PR DESCRIPTION
**Pull request by prasadns14**
Updated script to insert data into the tables.

We can't use external tables for all parquet files, as hive throws error for some parquet files (don't know the reason). So changed the script to create tables in those scenarios.

@Agirish please review

### CODE REVIEW

**Comment by Agirish** [comment]
@prasadns14, can we figure out why those fail. It'll be good for consistency reasons. Also, we'd not want a huge data gen job to go through - instead of just pointing to a location via creating an external table

**Comment by Agirish** [comment]
@prasadns14, is more work pending for this PR?

**Comment by prasadns14** [comment]
@Agirish, all tests pass now

**Comment by Agirish** [comment]
+1. Thanks Prasad. Will we need this on other branches?

**Pull request merged**
