### PR TITLE
MD-734: Removed multiple copies of execHive.sh

### PR DESCRIPTION
**Pull request by prasadns14**
@cchang738, please review the PR
I have retained a single copy of execHive.sh under framework/resources/bin, and changed all usages of the script to use the one in this directory.

### CODE REVIEW

**Comment by cchang738** [comment]
Possible to put this script under framework/scripts? The bin dir is for scripts to launch the framework.

**Comment by Agirish** [comment]
We should move it under Datasources/hive_storage

**Comment by prasadns14** [comment]
Changed the location of execHive.sh to Datasources/hive/execHive.sh

**Comment by Agirish** [comment]
Thanks Prasad. +1.

**Pull request merged**
