### PR TITLE
Added tests for DRILL-4862

### PR DESCRIPTION
**Pull request by khurram-faraaz**
Hello Abhishek,

I have added tests to verify fix for DRILL-4862
You should look at framework/resources/Functional/convert/drill_4862*.q tests

Please review and merge, I have a clean run where my new test have passed, there are other unrelated failures in that run. I will share the link to that pre-commit run.

Thanks,
Khurram

### CODE REVIEW

**Comment by Agirish** [comment]
HEy Khurram, 

Looks like there are over 10 commits in here. Can you please do the following:
- add mapr/master as a remote, if you haven't done so already
  `git remote add mapr git@github.com:mapr/drill-test-framework.git`
- create a new branch 
  `git checkout -b BRANCH_NAME
- rebase it over mapr/master 
  `git rebase mapr/master`
- add files part of this check-in
  `git add FILE_NAME`
- commit them
  `git commit -m "MESSAGE"`
- push them to a new branch
  `git push origin BRANCH_NAME`
- create a PR from this branch via Github

**Comment by kfaraaz** [comment]
Those others commits that are showing up were the ones we already merged in an earlier PR. Those were tests for null equality join support. 
I think the HEAD got changed/messed up somehow on my machine, while I was trying to build different versions of Drill.
Is it not possible that we can fix the HEAD on my current repo on my machine ? That will save me some time. 
I have never had this kind of issue before, only after the HEAD was changed I have started to see these issues.

Thanks,
Khurram

**Comment by Agirish** [comment]
If you already have them committed in your fork and you think your master is messed up, 

To clean up master on your fork:
- add mapr/master as a remote, if you haven't done so already
   `git remote add mapr git@github.com:mapr/drill-test-framework.git`
- fetch or pull mapr
   `git pull mapr master`
- rebase your master over mapr/master
    `git rebase mapr/master`

Since you have new commits, before you raise a PR,
- create a new branch from your updated master branch
   `git checkout -b BRANCH_NAME`
- rebase it again interactively and squash all related commits into one. 
  `git rebase -i HEAD~10` 
   Assuming after rebase over master you have 10 new commits in your branch. Retain 'pick' on the earliest and most relevant commit. Change 'pick' to 's' on each line for a related commit. Save it. Then once rebase starts, edit the commit message to remove all messages above the instructions, except for the most relevant message.
- force push this to your new branch
   `git push -f origin BRANCH_NAME`

**Comment by kfaraaz** [comment]
However, we see this message when I did a compare of the two branches, " Able to merge. These branches can be automatically merged."
So I would assume that it is safe to merge, given that there are no conflicts & we have a clean pre-commit run.

Thanks,
Khurram

**Pull request closed without merging**
