### PR TITLE
Handle map NPE to meaningful IOException

### PR DESCRIPTION
**Pull request by abhidotravi**
- Handle NullPointerException and throw the right exception with meaningful cause.
- Remove bad formatting in associated methods.

This PR solves the issue https://github.com/mapr/drill-test-framework/issues/545

### CODE REVIEW

**Comment by aravi5** [comment]
The most important change here is changing following snippet
```
	for (File file : root.listFiles()) {
	  ...
	  ...
	}
```

to 
```
      File[] files = root.listFiles();
      if (files != null) { //Directory exists
        for (File file : files) {
          ...
          ...
        }
      } else {
        throw new FileNotFoundException("Pathname, \"" + root.getPath() + "\"" +
                " does not exist or does not denote a directory");
      }
```

Rest is reformatting since these methods had bad formatting.

**Comment by Agirish** [comment]
Hey @aravi5 , thanks for making the changes. Could you kindly remove all formatting changes in this PR? That way the diff would be clean. We could make the formatting changes (if required) in a diff PR.

**Comment by aravi5** [comment]
Done.

**Comment by aravi5** [comment]
Yes. I had verified that the fix works as expected, before submitting the PR.
```java.io.FileNotFoundException: Pathname, "/root/drilldockerhome/drill-test-framework/framework/framework/resources" does not exist or does not denote a directory
	at org.apache.drill.test.framework.Utils.getTestDefinitionList(Utils.java:359)
	at org.apache.drill.test.framework.Utils.getTestDefSources(Utils.java:197)
	at org.apache.drill.test.framework.Utils.getDrillTestCases(Utils.java:227)
	at org.apache.drill.test.framework.TestDriver.runTests(TestDriver.java:174)
	at org.apache.drill.test.framework.TestDriver.main(TestDriver.java:93)```

**Pull request merged**
