### PR TITLE
DRILL-4759: add a test coverage

### PR DESCRIPTION
**Pull request by cchang738**
@krystaln Can you please review this PR? Thanks.

http://10.10.104.91:8080/job/Framework-Regression/888/console

### CODE REVIEW

**Comment by krystaln** [comment]
LGTM +1

**Comment by kfaraaz** [comment]
@cchang738  Did we set store.parquet.enable_dictionary_encoding to TRUE in the test, so that way dictionary encoding is enabled ?

**Comment by cchang738** [comment]
@kfaraaz The test does not create data. Test data already in proper form. But thanks for the comment.

**Comment by kfaraaz** [comment]
@cchang738 thanks for confirming, I asked this because in DRILL-4759 the issue was hit over dictionary encoded parquet data.

**Pull request merged**
