### PR TITLE
DRILL-6173: Added tests to verify transitive closure during filter pu…

### PR DESCRIPTION
**Pull request by denysord88**
…sh down and partition pruning

### CODE REVIEW

**Comment by denysord88** [comment]
@Agirish could you review my fixed pull request please?

**Comment by Agirish** [comment]
+1, thanks for addressing the issue. LGTM. I'll have it run through regression tests and then merge it in.

**Comment by denysord88** [comment]
@Agirish I updated my commit. Could you review it again please?

**Comment by Agirish** [comment]
Hey @denysord88 , I saw more failures - can you take a look (details emailed)?

**Comment by denysord88** [comment]
Trying to run all Functional tests on test cluster to find conflicts of decimal tests with others.

**Comment by denysord88** [comment]
I updated last commit, added secure drill URL with password to gen script framework/resources/Datasources/ctas/Transitive_closure_gen.sh

@cchang738 could you please review this pull request?

**Comment by kedarbcs16** [comment]
framework ran with 84 failures

**Comment by kedarbcs16** [comment]
@denysord88 sent you a mail regarding the same

**Comment by denysord88** [comment]
I found the reason of that errors. I used folder "/drill/testdata/ctas/parquet" in hadoop fs, but in another script "Datasources/ctas/create_tables.sh" this folder deleting and then creating again. That script delets my csv files.
I changed folders of my CSV files for CTAS.
@kedarbcs16  Could you please run again pre-commit functional tests? On our CV Test cluster we don't get errors with Transitive Closure now.

**Comment by kedarbcs16** [comment]
@Agirish I see failures but I don't think they are @denysord88 's failures .

**Comment by denysord88** [comment]
@Agirish if there are no test failures with transitive closure, could you merge this PR to the master please?

**Pull request merged**
