### PR TITLE
Updating TPC-DS Scripts

### PR DESCRIPTION
**Pull request by agirish**

### CODE REVIEW

**Comment by Agirish** [comment]
@prasadns14 , can you please take a look?

**Comment by prasadns14** [comment]
@Agirish do you think we can use su $user irrespective of whether the user is root or otherwise?

**Comment by Agirish** [comment]
That's a good idea. Let me think and get back

**Comment by Agirish** [comment]
That doesn't seem to work. We need to handle root user differently.

**Comment by prasadns14** [comment]
+1

**Pull request merged**
