### PR TITLE
DRILL-6259: Added tests and data to verify that filter pushdown works…

### PR DESCRIPTION
**Pull request by agozhiy**
… with complex fields.

Also, changed extensions of the plan verification tests to separate them from the parent test suite.

### CODE REVIEW

**Comment by cchang738** [comment]
@agozhiy PR looks good. How was the test data files generated? specifically, parquet complex data types. Thanks.

**Comment by Agirish** [comment]
@agozhiy, I see some of the files have .sql_no as extension. We are trying to standardize on .sql as the extension, so can you perhaps move these to a new directory instead? This is more readable. 

Also instead of .res_no, it's preferred to stick to ".e_tsv" (expected tab separated values). For plan baselines, i'm recommending to standardize on ".plan".

**Comment by agozhiy** [comment]
@cchang738, I used parquet-mr tools to create complex data:
https://github.com/apache/parquet-mr

**Comment by agozhiy** [comment]
@Agirish, done as you said, please review

**Comment by Agirish** [comment]
Thanks for making the changes @agozhiy. For Plan verification tests, we should start using .plan as the extension going forward. One of us can work on applying that retroactively for existing tests later. 

+1. LGTM.

**Pull request merged**
