### PR TITLE
Running the same test multiple times

### PR DESCRIPTION
**Pull request by rchallapalli**
Chun/Abhishek,

I added the ability where we can run the same test multiple times. I also added a suite for network intensive queries. Let me know your thoughts.
- Rahul

### CODE REVIEW

**Comment by Agirish** [comment]
Hey Rahul, 

I think it would be good to separate the test cases from framework code. Should we make them as independent commits?

**Comment by rchallapalli** [comment]
Sure Abhishek. I can do that

**Comment by cchang738** [comment]
Rahul,

I think we can implement this feature in a much simpler way. No need to create new class and interface. Just a very simple change to existing DrillTestJdbc.java and TestDriver.java. I will discuss this with you in person.

Chun

**Comment by rchallapalli** [comment]
Folks,

I am closing this PR. I will create a new PR which has different commits for the framework changes and the tests themselves

**Pull request closed without merging**
