### PR TITLE
Fixing Hive Avro scripts for Hive 0.13 & an issue with cross-sources suite

### PR DESCRIPTION
**Pull request by agirish**

### CODE REVIEW

**Comment by Agirish** [comment]
Rahul, can you please take a look? Had a successful run on my system. I'll schedule a test run on the common cluster and will let you know if i see issues.

**Comment by rchallapalli** [comment]
Looks good. Merge it once you get a successfull run

**Comment by Agirish** [comment]
@rchallapalli, I also made a change to fix the issue with the cross-sources suite. Can you take a look? I've scheduled another run with this commit.

**Comment by Agirish** [comment]
Got a clean run. Merging.

**Pull request merged**
