### PR TITLE
Merge bunch of tests + new TPCDS queries that we can run now

### PR DESCRIPTION
**Pull request by vmarkman**

### CODE REVIEW

**Comment by Agirish** [comment]
Taking a look.

**Comment by Agirish** [comment]
Can you take a look at 9003a8573ac0866bc2c8c750d2f5c8ae53e59298 (the datagen scripts)

**Comment by Agirish** [comment]
Otherwise, looks good. Thanks for the adding the tests. +1

**Comment by vmarkman** [comment]
I'm going to rerun Functional and Advanced tests as well before merging. 
Thank you for taking time to review these changes.

**Comment by vmarkman** [comment]
I had two clean Functional and Advanced runs.

**Pull request merged**
