### PR TITLE
Modify baselines for DRILL-4194

### PR DESCRIPTION
**Pull request by vkorukanti**
DRILL-4194 changed the expected output for HiveScan. Changed the baselines accordingly. Running a regression test: http://10.10.104.91:8080/job/Framework%20Regression/273/

### CODE REVIEW

**Comment by Agirish** [comment]
+1 from me, but I think Rahul should take a look at this.

**Comment by rchallapalli** [comment]
There are some failures with the modified tests. I think there are still some issues with escaping

**Comment by vkorukanti** [comment]
Here is the successful run. Had to modify the pattern for escaping some special characters.

**Comment by rchallapalli** [comment]
Thanks venki

**Pull request merged**
