### PR TITLE
DRILL-5822: Verify that ORDER BY / ORDER BY DESC clauses don't change…

### PR DESCRIPTION
**Pull request by omalashevsky**
… cols order if planner.slice_target=1

### CODE REVIEW

**Comment by Agirish** [comment]
Please change "alter session set planner.slice_target = 1;" to simply "set planner.slice_target = 1;". Similarly for others. Also change the reversal of defaults to "reset planner.slice_target"

**Comment by omalashevsky** [comment]
The tests have been updated, please review.
Thanks

**Comment by Agirish** [comment]
+1. Thanks @omalashevsky. Let me schedule a test run and if it goes through, i'll merge this.

**Comment by Agirish** [comment]
@omalashevsky, I've merged the PR. Kindly cherry-pick this for branch 1.12.0-mapr

**Comment by omalashevsky** [comment]
The commit has been cherry-picked

**Pull request merged**
