### PR TITLE
MD-3028: Create jdbc connection with/without plain authenticaion

### PR DESCRIPTION
**Pull request by prasadns14**
Create jdbc connection without username and password if password not set in drillTestConfig

@Agirish please review

### CODE REVIEW

**Comment by Agirish** [comment]
Hey Prasad, thanks for making this change. Before we merge it in, can we do a quick try with password key commented out or set to double quotes.

**Comment by prasadns14** [comment]
@Agirish I tried both the suggestions, but they don't solve the issue.

**Comment by Agirish** [comment]
Can you please rebase your change on mapr master / 1.11.0-mapr?

**Comment by prasadns14** [comment]
Created a new PR for 1.11.0-mapr

**Pull request closed without merging**
