### PR TITLE
Updating query plan to pick StreamAgg

### PR DESCRIPTION
**Pull request by agirish**

### CODE REVIEW

**Comment by Agirish** [comment]
@kkhatua , @cchang738 can one of you please take a quick look? This is currently only being put into the 1.13.0-mapr branch.

**Comment by kkhatua** [comment]
I'm guessing the indentation is anyway ignored by the framework.
LGTM.

**Comment by Agirish** [comment]
Yes, the regex handles that.

**Comment by Agirish** [comment]
Thanks Kunal!

**Pull request merged**
