### PR TITLE
Tests on top of hive generated parquet files

### PR DESCRIPTION
**Pull request by rchallapalli**
Chun & Abhishek,

Below are the tests I added
1. Functional : Generated parquet files from hive to cover the supported data types and added test cases around that
2. Advanced : Generated tpcds 1 parquet files using hive and added tpcds queries. Same suite is repeated for the hive plugin, native reader, and directly reading through the dfs storage plugin.

I got clean functional[1] and advanced[2] runs (known connection loss failures) using the latest commit. Kindly review the changes

[1] http://10.10.104.91:8080/view/Pre-commit%20Results/job/Framework-Regression/416/console
[2] http://10.10.104.91:8080/view/Pre-commit%20Results/job/Framework-Regression-Advanced/74/console

Rahul

### CODE REVIEW

**Comment by Agirish** [comment]
- Verified tests under Advanced/tpcds_sf1/hive-generated-parquet
- Verified workspaces created in dfs-storage-plugin.template for the above tests
- Verified test def files for each test suite
- Verified session options for hive native scan is enabled before test and disabled after. 
- Verified Hive DDL scripts. 
  -- Hive Native and Hive Plugin test suites (for each version) call the same script   But as per our discussion recently, this shouldn't cause concurrency problem since framework should ideally execute them just once. 
  -- In the DDL some tables have TBLPROPERTIES defined, where as others don't. I remember you mentioning that this was as designed (for giving a variety of file types). Wanted to confirm with you. 

- Can you remove Advanced/tpcds/tpcds_sf1/hive-generated-parquet/hive1dot2_parquet/jstack.txt
- Can you remove Regression run URLs from the PR desc (since they aren't accessible outside). You can share it with us over email or chat.

**Comment by Agirish** [comment]
- Verified regression run.

**Comment by rchallapalli** [comment]
Thanks for your review Abhishek. Thanks for pointing out the jstack file. I removed it and pushed the changes.

Some hive tables do not use TBLPROPERTIES and this is intentional so that we test the hive's parquet writer with its default settings.

I will update the PR to remove the links to functional and advanced runs

Rahul

**Comment by Agirish** [comment]
Looked at tests in Functional as well. 

LGTM. +1

**Comment by rchallapalli** [comment]
Thanks for the review abhishek

**Pull request merged**
