### PR TITLE
Test cases for schema change due to empty batch

### PR DESCRIPTION
**Pull request by prasadns14**
1) Added test cases for schema change due to null batch
2) Added a getter for drillProperties

Marked cases related to known issues as fail.

### CODE REVIEW

**Comment by cchang738** [comment]
1. Please provide pre-commit test link;
2. How much time added to test run?
3. Framework has a mode to only run tests marked failed. Make sure in that mode, framework picks up your failed tests.

**Comment by Agirish** [comment]
Any reason for having a new plugin template: lfs-storage-plugin.template?

**Comment by Agirish** [comment]
Can you change "null batch" to empty batch" throughout the PR? I think that's more used terminology.

**Comment by Agirish** [comment]
Also, please share the pre-commit test run URL over email.

**Comment by Agirish** [comment]
Thanks Prasad. +1

**Comment by prasadns14** [comment]
@cchang738 Time added to test run - ~8 mins

**Pull request merged**
