### PR TITLE
Supporting Hive 1.2

### PR DESCRIPTION
**Pull request by agirish**
(1) Updated TPC-DS datasets on Amazon S3
(2) Updated TPC-DS suites to use updated datasets
(3) Updated TPC-DS scripts
(4) Added new TPC-DS suites for JSON datasets
(5) Updated some Hive suites to support Hive 1.2
(6) Updated Aggregates (TPC-DS) suites
(7) Updated Window Function (TPC-DS) suites
(8) Fixed & moved TPC-DS Original suite from Advanced to Functional

### CODE REVIEW

**Comment by Agirish** [comment]
Rahul, Please take a look. I have a few more fixes coming in, so to make it easier to review, I thought  i"ll have you start with what's ready.

**Comment by Agirish** [comment]
Got successful runs on test cluster.

**Comment by rchallapalli** [comment]
I reviewed the first series of commits and they look good. Will review the second batch of commits tomorrow.

**Comment by rchallapalli** [comment]
Abhishek,

These changes are very welcome. Also thanks for taking time to cleanup the tpcds suites. Considering the amount of file modified, I would appreciate if we can get a clean run on each of our clusters just to be sure.

- Rahul

**Comment by Agirish** [comment]
Thanks Rahul. I've got two runs already. Will schedule a few more and then merge them.

**Comment by Agirish** [comment]
Rahul, regarding your comment on time taken by TPC-DS SF1 Original queries - I think they are well within the average. Did not see any issues. Will also monitor them for a few runs to be sure.

**Pull request merged**
