### PR TITLE
Updated some Hive tests to include Hive as dependency

### PR DESCRIPTION
**Pull request by agirish**

### CODE REVIEW

**Comment by rchallapalli** [comment]
Thanks for fixing these abhishek.

There are 41 commits in the PR. That makes it hard to review. Can you possibly squash them?

**Comment by Agirish** [comment]
Sorry, it was fine when I created the PR - i just screwed up something now. I'll update this shortly.

**Comment by Agirish** [comment]
@rchallapalli, this should be fixed. Please review. I'll have a test run and merge if successful.

**Comment by Agirish** [comment]
Specifically, please confirm if all these do indeed have hive dependency. If not i'll correct them.

**Comment by rchallapalli** [comment]
LFTM +1

**Comment by Agirish** [comment]
Thanks Rahul

**Pull request merged**
