### PR TITLE
Added functional tests for temporary table support

### PR DESCRIPTION
**Pull request by khurram-faraaz**
Hi Abhishek,

Can you please review these tests that verify temporary table support.
I will share link to pre-commit run once it is complete, in a separate email.

Thanks,
Khurram

### CODE REVIEW

**Comment by Agirish** [comment]
Taking a look.

**Comment by kfaraaz** [comment]
Two new tests have failed due to below Exception. We need to fix this in the test framework.

Execution Failures:
/root/drillAutomation/framework/framework/resources/Functional/cttas/cttas_22.sql
Query: 
null
Failed with exception
org.apache.drill.jdbc.AlreadyClosedSqlException: ResultSet is already closed.
	at org.apache.drill.jdbc.impl.DrillResultSetImpl.throwIfClosed(DrillResultSetImpl.java:127)
	at org.apache.drill.jdbc.impl.DrillResultSetImpl.next(DrillResultSetImpl.java:164)
	at org.apache.drill.test.framework.DrillTestJdbc.executeSetupQuery(DrillTestJdbc.java:163)
	at org.apache.drill.test.framework.DrillTestJdbc.run(DrillTestJdbc.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
/root/drillAutomation/framework/framework/resources/Functional/cttas/cttas_22_b.sql
Query: 
null
Failed with exception
org.apache.drill.jdbc.AlreadyClosedSqlException: ResultSet is already closed.
	at org.apache.drill.jdbc.impl.DrillResultSetImpl.throwIfClosed(DrillResultSetImpl.java:127)
	at org.apache.drill.jdbc.impl.DrillResultSetImpl.next(DrillResultSetImpl.java:164)
	at org.apache.drill.test.framework.DrillTestJdbc.executeSetupQuery(DrillTestJdbc.java:163)
	at org.apache.drill.test.framework.DrillTestJdbc.run(DrillTestJdbc.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by kfaraaz** [comment]
I have fixed the two failing tests and we have a clean pre-commit run, I have a link to pre-commit run. Please take a look. Thanks.

**Comment by Agirish** [comment]
@kfaraaz, let's not get this in, unless we are sure we won't see the tests failing again. Can you detail on what specifically was the issue that you fixed? We wouldn't want any random failures in the Pre-commit runs.

**Comment by kfaraaz** [comment]
@Agirish I have shared details in an email about the test case fix, and I also have two separate pre-commit clean runs. All new CTTAS tests pass in both the runs.

**Comment by Agirish** [comment]
@kfaraaz can you confirm how the baselines were created?

**Comment by Agirish** [comment]
Also, can you share the test plan over email?

**Comment by kfaraaz** [comment]
@Agirish baseline expected results were created by running the queries against Postgres 9.3. Temporary tables were created manually in Postgres and expected results were generated.

**Comment by kfaraaz** [comment]
You have access to the test plan ( CTTAS_test_plan_v2 ) since you had reviewed it earlier.

**Comment by Agirish** [comment]
Thanks for confirming @kfaraaz. 
+1 LGTM

**Comment by kfaraaz** [comment]
Thanks @Agirish

**Pull request merged**
