### PR TITLE
Baseline updates for filter pushdown plan test after DRILL-6574

### PR DESCRIPTION
**Pull request by denysord88**
Need to be merged after Drill PR https://github.com/apache/drill/pull/1386

### CODE REVIEW

**Comment by kkhatua** [comment]
@rhou1 can you review this?

**Comment by rhou1** [comment]
Denys, the plan introduces a sort.  Is this expected?

**Comment by denysord88** [comment]
@rhou1 yes, sort is expected.

**Comment by KazydubB** [comment]
Yes, after the optimization (added limit just before scan), cost for StreamAgg + Sort + Limit + Scan is lower (40152.0 CPU and 16.0 memory) than it is for HashAgg + Limit + Scan (40161.0 CPU and 26.4 memory).

**Comment by Agirish** [comment]
+1. LGTM. If Robert has no more concerns, we can have this merged.

**Comment by rhou1** [comment]
+1.  Thanks for the explanation.

**Comment by arina-ielchiieva** [comment]
@rhou1 I think we merged this fix prematurely. I should have been merged after Drill PR apache/drill#1386 :) Now we can expect this test to fail.

**Comment by Agirish** [comment]
I just opened a PR to revert it. Once the Drill PR is merged, we can revert the revert :)

**Comment by rhou1** [comment]
Sorry, Boaz gave me the impression that this PR was preventing DRILL-6574 from being committed.  So I approved this PR and was in the process of updating the framework so Boaz could get a clean run.

I have stopped the framework update and approved the revert.

**Comment by arina-ielchiieva** [comment]
@denysord88 could you please open new PR with the same changes?

**Comment by denysord88** [comment]
PR with the same changes https://github.com/mapr/drill-test-framework/pull/489 created

**Comment by denysord88** [comment]
Created PR https://github.com/mapr/drill-test-framework/pull/490

**Pull request merged**
