### PR TITLE
MD-158, refactoring code. a new class to model testcase

### PR DESCRIPTION
**Pull request by cchang738**
This pull request:
1. streamline test case class. This eliminates the need to duplicate test case modeler for every query.
2. remove JsonTestDataProvider.java and move it's function to Utils.java.
3. some other minor code changes

Please review. Pre-commit run at http://10.10.104.91:8080/job/Framework%20Regression/260/console

### CODE REVIEW

**Comment by cchang738** [comment]
The first pre-commit run failed during data creation (not related to my change). Here is another run: http://10.10.104.91:8080/job/Framework%20Regression/261/console

**Comment by cchang738** [comment]
second pre-commit run exposed a bug. Here is the third run: http://10.10.104.91:8080/job/Framework%20Regression/262/console

**Comment by cchang738** [comment]
third pre-commit run failed again at data gen. here is the fourth run: http://10.10.104.91:8080/job/Framework%20Regression/264/console

**Comment by cchang738** [comment]
Added teardown phase. New pre-commit run:

http://10.10.104.91:8080/job/Framework%20Regression/277/console

**Comment by cchang738** [comment]
Latest pre-commit run. I will merge by end of day if no one cares. It's been sitting here for too long. :)

http://10.10.104.91:8080/job/Framework%20Regression/330/console

**Comment by Agirish** [comment]
Taking a look now.

**Comment by Agirish** [comment]
Looks good. Thanks for making this change.

In TestDriver we might be able to reuse the teardown method (can be renamed) for executing both before-run.sql and after-run.sql, so that the setup method can make use of this part too.

**Comment by cchang738** [comment]
thanks.

**Pull request merged**
