### PR TITLE
DRILL-7050 - Testing subqueries in the SELECT statement.

### PR DESCRIPTION
**Pull request by denysord88**

### CODE REVIEW

**Comment by denysord88** [comment]
@Agirish could you please review this PR?

**Comment by Agirish** [comment]
@denysord88 , can you please share why we are using both cp and dfs storage plugins? Also the dfs table has same data as the one in cp - so trying to understand.

Otherwise, looks good. +1

**Comment by denysord88** [comment]
> @denysord88 , can you please share why we are using both cp and dfs storage plugins? Also the dfs table has same data as the one in cp - so trying to understand.
> 
> Otherwise, looks good. +1

I just want to check JOIN tables from different workspaces in the subquery. I think it may cause some issues and it will be good to have this test in our framework.

**Comment by Agirish** [comment]
I'd like to avoid unnecessary data
Gen scripts if possible. So if this can be reworked to use an existing DFS table, it would be good. It's just easy for overall maintenance. And for overall storage footprint.

**Comment by Agirish** [comment]
On second thoughts, since this is a small dataset, let's get it in. But please be mindful Ruth future PRs. More scripts and more data is more maintenance

**Pull request merged**
