### PR TITLE
Enabling decimal type and printing version 

### PR DESCRIPTION
**Pull request by agirish**
Chun, can you please review?

### CODE REVIEW

**Comment by Agirish** [comment]
Thanks Vicky. Updated that.

**Comment by cchang738** [comment]
I also synced up with Ahbishek on an issue. He made the changes already.

**Comment by Agirish** [comment]
Test run was successful (except for a few random and unrelated failures). Discussed with Chun.

**Comment by Agirish** [comment]
Thanks Chun. Merging.

**Pull request merged**
