### PR TITLE
MD-3149: add drop table if exists

### PR DESCRIPTION
**Pull request by cchang738**
@prasadns14 Can you review this PR?

http://10.10.104.91:8080/job/Framework-Regression/1149/console

### CODE REVIEW

**Comment by cchang738** [comment]
http://10.10.104.91:8080/job/Framework-Regression/1150/console

**Comment by prasadns14** [comment]
Its a good improvement to increase the chances of cleanup. To actually know if the changes reduce random failures, we need to have a fair number of runs. Lets get this PR checked in to test it out.
LGTM, +1

**Comment by rhou1** [comment]
Would we want to consider disabling the re-connection code if Dev wants to debug why the connection is dropped?

**Comment by cchang738** [comment]
It should not affect any debug effort. Connection drop is still reported. Re-connection only happens for cleanup purpose.

**Pull request merged**
