### PR TITLE
MD-4591: Baselines updates due to changes in DRILL-6492

### PR DESCRIPTION
**Pull request by agozhiy**

### CODE REVIEW

**Comment by agozhiy** [comment]
Need to be merged after the following Drill PR:
https://github.com/apache/drill/pull/1338

**Comment by Agirish** [comment]
+1. LGTM

**Comment by arina-ielchiieva** [comment]
PR is merged (https://github.com/apache/drill/pull/1338) into Apache master. Please merge baselines update as well.

**Comment by Agirish** [comment]
I'll run through tests and have it merged shortly.

**Pull request merged**
