### PR TITLE
MD-4650: Updated baselines due to changes in DRILL-6575

### PR DESCRIPTION
**Pull request by agozhiy**

### CODE REVIEW

**Comment by agozhiy** [comment]
Need to be merged after the following PR:
https://github.com/apache/drill/pull/1365

**Comment by arina-ielchiieva** [comment]
apache/drill#1365 is already merged into Apache master.
@kkhatua / @Agirish please review and merge the PR.

**Comment by kkhatua** [comment]
I'm presuming the new format is consistent for this Hive version onwards, or else we might have to change the way to verify this.
LGTM otherwise.
+1

**Comment by kkhatua** [comment]
It looks like the order of the keys is the only change. I'm hoping this remains consistent. 
LGTM +1

**Pull request merged**
