### PR TITLE
MD-569: Framework now able to run a set of sql statement before test starts

### PR DESCRIPTION
**Pull request by cchang738**
This is a nice enhancement to framework to provide the functionality documented in MD-569. Lay groundwork to handle MD-158.

Pre-commit test run can be viewed here. Please review.

http://10.10.104.91:8080/job/Impersonation%20Regression/7/console

### CODE REVIEW

**Comment by Agirish** [comment]
Hey Chun, 

This is a good feature addition - should also help when we plan on extending this to per suite level. 

Can we move the "before-test.sql" file inside the `scripts/sqlScripts` directory? And possible rename it to something different - say like "initialize.sql" - since this isn't test specific, but for the whole run. 

Also, lets avoid on sharing private links - i had a look at the test run results - they look good.

**Comment by cchang738** [comment]
Thanks for the review and feedback. I feel the location of the file should not be in the scripts directory. It's not a script. Also, it's more logical to have the file in the same directory where the run.sh is (where you start the run). I do agree on the suggestion on changing the file name. How about "before-run.sql"? I will add corresponding "after-run.sql", "before-test.sql" and "after-test.sql" in a future enhancement.

**Comment by cchang738** [comment]
Changed default pre-run query filename to "before-run.sql". Looking for a +1. :)

**Comment by Agirish** [comment]
+1. I would still prefer if the query script file was moved to the sqlScripts directory, to keep the framework dir clean. But I guess we could do it another time.

**Comment by cchang738** [comment]
Ahbishek, I will sync up with you on your point offline. Thanks for review.

**Pull request merged**
