### PR TITLE
Fixing test result baselines (TPC-H SF1 dataset)

### PR DESCRIPTION
**Pull request by agirish**

### CODE REVIEW

**Comment by cchang738** [comment]
Do you understand what caused the baseline change for query25_min.e_tsv?

**Comment by Agirish** [comment]
The results for query 25 have been verified with Greenplum.

**Comment by cchang738** [comment]
OK. Thanks. +1

**Comment by Agirish** [comment]
Not sure. But the new values were verified with Postgres.

**Pull request merged**
