### PR TITLE
Verify

### PR DESCRIPTION
**Pull request by rchallapalli**
Khurram,

I verified a few more bugs and added test cases for them. Below is the functional run URL. The failures are known failures. Can you take a look?

http://10.10.104.91:8080/job/Framework%20Regression/290/console

Rahul

### CODE REVIEW

**Comment by Agirish** [comment]
Rahul, could you update the addremove_files.sh file to have an if/else structure to check if directory exists before you create or delete them?

**Comment by Agirish** [comment]
Other than that, looks good.

**Comment by rchallapalli** [comment]
Abhishek,

Made the suggested change and the functional run did not have any issues. Can you take a look?

Rahul

**Comment by Agirish** [comment]
LGTM, +1

**Pull request merged**
