### PR TITLE
DRILL-5880: Marking as failed

### PR DESCRIPTION
**Pull request by prasadns14**
These test cases are related to DRILL-5880. Marking them as failed.
@Agirish please review

### CODE REVIEW

**Comment by prasadns14** [comment]
@rhou1 please verify

**Comment by rhou1** [comment]
We also want to include the ".q" suffix.  So something like this:

query5825_5880.q.fail

So with the -rF option, the framework will strip off ".fail" and run query5825_5880.q as a normal test.

**Comment by prasadns14** [comment]
@rhou1 changes made

**Comment by rhou1** [comment]
+1 LGTM.

**Comment by Agirish** [comment]
+1. Thanks Prasad.

**Pull request merged**
